service: <YOUR_SERVICE_NAME>

custom:
  defaultStage: prod
  defaultProfile: default
  defaultURL: <YOUR_KINTONE_URL>
  defaultAppId: <YOUR_APP_ID>
  defaultAPIToken: <YOUR_API_TOKEN>

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - "*"
  environment:
    KINTONE_URL: ${self:custom.defaultURL}
    KINTONE_APPID: ${self:custom.defaultAppId}
    KINTONE_APITOKEN: ${self:custom.defaultAPIToken}

functions:
  func:
    handler: handler.main
    description: kintoneでリアルタイムアンケートのサーバーサイド処理
    events:
      - http:
          path: ${self:service}-func
          method: post
          cors: true
    environment:
      FUNCTION_NAME: ${self:service}-func
